package calcu_para_progra2;

/**
 *
 * @author ervargas
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Calculator = new javax.swing.JPanel();
        NumPad = new javax.swing.JPanel();
        Button1 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        Button7 = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        Button0 = new javax.swing.JButton();
        ButtonIgual = new javax.swing.JButton();
        DisplayPanel = new javax.swing.JPanel();
        PrincipalDisplayLabel = new javax.swing.JLabel();
        SecondDisaplayLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ButtonDivide = new javax.swing.JButton();
        ButtonMulti = new javax.swing.JButton();
        ButtonMenos = new javax.swing.JButton();
        ButtonPlus = new javax.swing.JButton();
        ButtonCE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(390, 517));
        getContentPane().setLayout(null);

        Calculator.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Calculator.setMinimumSize(new java.awt.Dimension(400, 500));
        Calculator.setPreferredSize(new java.awt.Dimension(400, 500));
        Calculator.setLayout(null);

        NumPad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        NumPad.setLayout(null);

        Button1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Button1.setText("1");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });
        NumPad.add(Button1);
        Button1.setBounds(10, 130, 70, 50);

        Button2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Button2.setText("2");
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });
        NumPad.add(Button2);
        Button2.setBounds(90, 130, 70, 50);

        Button3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Button3.setText("3");
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });
        NumPad.add(Button3);
        Button3.setBounds(170, 130, 70, 50);

        Button4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Button4.setText("4");
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });
        NumPad.add(Button4);
        Button4.setBounds(10, 70, 70, 50);

        Button5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Button5.setText("5");
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });
        NumPad.add(Button5);
        Button5.setBounds(90, 70, 70, 50);

        Button6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Button6.setText("6");
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });
        NumPad.add(Button6);
        Button6.setBounds(170, 70, 70, 50);

        Button7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Button7.setText("7");
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });
        NumPad.add(Button7);
        Button7.setBounds(10, 10, 70, 50);

        Button8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Button8.setText("8");
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });
        NumPad.add(Button8);
        Button8.setBounds(90, 10, 70, 50);

        Button9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Button9.setText("9");
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });
        NumPad.add(Button9);
        Button9.setBounds(170, 10, 70, 50);

        Button0.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Button0.setText("0");
        Button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button0ActionPerformed(evt);
            }
        });
        NumPad.add(Button0);
        Button0.setBounds(10, 190, 70, 50);

        ButtonIgual.setBackground(new java.awt.Color(0, 204, 51));
        ButtonIgual.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        ButtonIgual.setText("=");
        ButtonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIgualActionPerformed(evt);
            }
        });
        NumPad.add(ButtonIgual);
        ButtonIgual.setBounds(90, 190, 150, 50);

        Calculator.add(NumPad);
        NumPad.setBounds(10, 220, 250, 250);

        DisplayPanel.setBackground(new java.awt.Color(0, 0, 0));
        DisplayPanel.setLayout(null);

        PrincipalDisplayLabel.setFont(new java.awt.Font("Dialog", 0, 50)); // NOI18N
        PrincipalDisplayLabel.setForeground(new java.awt.Color(0, 204, 0));
        PrincipalDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DisplayPanel.add(PrincipalDisplayLabel);
        PrincipalDisplayLabel.setBounds(6, 60, 330, 60);

        SecondDisaplayLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        SecondDisaplayLabel.setForeground(new java.awt.Color(0, 204, 0));
        SecondDisaplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DisplayPanel.add(SecondDisaplayLabel);
        SecondDisaplayLabel.setBounds(10, 10, 330, 40);

        Calculator.add(DisplayPanel);
        DisplayPanel.setBounds(10, 20, 350, 130);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        ButtonDivide.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        ButtonDivide.setText("/");
        ButtonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDivideActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonDivide);
        ButtonDivide.setBounds(20, 10, 50, 40);

        ButtonMulti.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        ButtonMulti.setText("X");
        ButtonMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMultiActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonMulti);
        ButtonMulti.setBounds(20, 70, 50, 40);

        ButtonMenos.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        ButtonMenos.setText("-");
        ButtonMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMenosActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonMenos);
        ButtonMenos.setBounds(20, 140, 50, 40);

        ButtonPlus.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        ButtonPlus.setText("+");
        ButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPlusActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonPlus);
        ButtonPlus.setBounds(20, 200, 50, 40);

        Calculator.add(jPanel1);
        jPanel1.setBounds(270, 220, 90, 250);

        ButtonCE.setText("CE");
        ButtonCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCEActionPerformed(evt);
            }
        });
        Calculator.add(ButtonCE);
        ButtonCE.setBounds(277, 170, 80, 24);

        getContentPane().add(Calculator);
        Calculator.setBounds(3, -3, 370, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    float valor1 = 0, valor2 = 0;
    boolean CambioEstado = false;
    String operador = "";

    private String formatearFloat(float numero) {
        if (numero % 1 == 0) {
            return String.format("%.0f", numero);
        } else {
            return String.valueOf(numero);
        }
    }

    private void AlmacenarValores() {
        if (CambioEstado == false) {
            valor1 = Float.parseFloat(PrincipalDisplayLabel.getText());
        } else {
            valor2 = Float.parseFloat(PrincipalDisplayLabel.getText());
        }
    }

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        PrincipalDisplayLabel.setText(PrincipalDisplayLabel.getText() + "2");
        AlmacenarValores();
    }//GEN-LAST:event_Button2ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        PrincipalDisplayLabel.setText(PrincipalDisplayLabel.getText() + "6");
        AlmacenarValores();
    }//GEN-LAST:event_Button6ActionPerformed

    private void Button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button0ActionPerformed
        PrincipalDisplayLabel.setText(PrincipalDisplayLabel.getText() + "0");
        AlmacenarValores();
    }//GEN-LAST:event_Button0ActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        PrincipalDisplayLabel.setText(PrincipalDisplayLabel.getText() + "1");
        AlmacenarValores();
    }//GEN-LAST:event_Button1ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        PrincipalDisplayLabel.setText(PrincipalDisplayLabel.getText() + "3");
        AlmacenarValores();
    }//GEN-LAST:event_Button3ActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
        PrincipalDisplayLabel.setText(PrincipalDisplayLabel.getText() + "4");
        AlmacenarValores();
    }//GEN-LAST:event_Button4ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
        PrincipalDisplayLabel.setText(PrincipalDisplayLabel.getText() + "5");
        AlmacenarValores();
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
        PrincipalDisplayLabel.setText(PrincipalDisplayLabel.getText() + "7");
        AlmacenarValores();
    }//GEN-LAST:event_Button7ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
        PrincipalDisplayLabel.setText(PrincipalDisplayLabel.getText() + "8");
        AlmacenarValores();
    }//GEN-LAST:event_Button8ActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
        PrincipalDisplayLabel.setText(PrincipalDisplayLabel.getText() + "9");
        AlmacenarValores();
    }//GEN-LAST:event_Button9ActionPerformed

    private void ButtonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIgualActionPerformed
        float total = 0;
        valor2 = Float.parseFloat(PrincipalDisplayLabel.getText());

        switch (operador) {
            case "+":
                total = (valor1 + valor2);
                break;
            case "-":
                total = valor1 - valor2;
                break;
            case "x":
                total = valor1 * valor2;
                break;
            case "/":
                total = valor1 / valor2;
                break;        
    }//GEN-LAST:event_ButtonIgualActionPerformed
            SecondDisaplayLabel.setText(formatearFloat(valor1) + " " + operador + " " + formatearFloat(valor2) + " =");
            PrincipalDisplayLabel.setText(formatearFloat(total));
            valor1 = total;
            valor2 = 0; 
    }

    private void ButtonMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMultiActionPerformed
        CambioEstado = true;
        operador = "x";
        PrincipalDisplayLabel.setText("");
        SecondDisaplayLabel.setText(formatearFloat(valor1) + " " + operador);
    }//GEN-LAST:event_ButtonMultiActionPerformed

    private void ButtonMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMenosActionPerformed
        CambioEstado = true;
        operador = "-";
        PrincipalDisplayLabel.setText("");
        SecondDisaplayLabel.setText(formatearFloat(valor1) + " " + operador);
    }//GEN-LAST:event_ButtonMenosActionPerformed

    private void ButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPlusActionPerformed
        CambioEstado = true;
        operador = "+";
        PrincipalDisplayLabel.setText("");
        SecondDisaplayLabel.setText(formatearFloat(valor1) + " " + operador);
    }//GEN-LAST:event_ButtonPlusActionPerformed

    private void ButtonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDivideActionPerformed
        CambioEstado = true;
        operador = "/";
        PrincipalDisplayLabel.setText("");
        SecondDisaplayLabel.setText(formatearFloat(valor1) + " " + operador);
    }//GEN-LAST:event_ButtonDivideActionPerformed

    private void ButtonCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCEActionPerformed
        PrincipalDisplayLabel.setText("");
        SecondDisaplayLabel.setText("");
        valor1 = 0;
        valor2 = 0;
        CambioEstado = false;
    }//GEN-LAST:event_ButtonCEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button0;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton ButtonCE;
    private javax.swing.JButton ButtonDivide;
    private javax.swing.JButton ButtonIgual;
    private javax.swing.JButton ButtonMenos;
    private javax.swing.JButton ButtonMulti;
    private javax.swing.JButton ButtonPlus;
    private javax.swing.JPanel Calculator;
    private javax.swing.JPanel DisplayPanel;
    private javax.swing.JPanel NumPad;
    private javax.swing.JLabel PrincipalDisplayLabel;
    private javax.swing.JLabel SecondDisaplayLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
